### ISSUE TITLE
bug: Notification click

### ISSUE THREAD

**Issue by aanders77** [capawesome-team/capacitor-android-foreground-service#1]
**Plugin version:**

0.0.1

**Platform(s):**

Android

**Current behavior:**

Clicking on the notification takes me to the Android settings page for my app. (Where you can force close, see permissions, uninstall etc)

**Expected behavior:**

Clicking the notification should open the app itself, not the Android settings for it.

**Comment by robingenz** [comment]
@aanders77 Great idea! This feature is now available:
```
npm install @capawesome-team/capacitor-android-foreground-service@0.0.2
```
