### ISSUE TITLE
feat: Close button

### ISSUE THREAD

**Issue by aanders77** [capawesome-team/capacitor-android-foreground-service#2]
It would be really nice to have an option to add a "Close app"-button to the foreground notification.

**Comment by robingenz** [comment]
This is also a great idea! I will look into it the next days.

**Comment by aanders77** [comment]
@robingenz Did you get a chance to look at this? My client asked for this excact feature today 🙂

**Comment by robingenz** [comment]
Sorry for not getting back to you. I plan to implement this feature this week.

**Comment by aanders77** [comment]
No worries. Thanks :)

**Comment by robingenz** [comment]
This is now supported in version `0.2.0`.

This is the implementation commit in the demo app: https://github.com/robingenz/capacitor-plugin-demo/commit/7317d358095d94297ce0007a1a6fab5287e79076

https://user-images.githubusercontent.com/13857929/224537512-65e354f2-e8e6-442a-871a-6a339c401828.mp4

**Comment by aanders77** [comment]
Thank you @robingenz , works perfectly.
